apiVersion: v1
kind: Service
metadata:
  name: flutter-web-service
  labels:
    app: flutter-web
spec:
  type: ClusterIP
  selector:
    app: flutter-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
